version: '3.8'

services:
  rest:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/db?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  mysql_data: